### ISSUE TITLE
Puppet Tasks Discussion

### ISSUE THREAD

**Issue by TraGicCode** [TraGicCode/tragiccode-wsusserver#11]
I think there are some maintenance tasks that could be implemented as puppet tasks in the module.  These tasks are the following:

1. Manual Synchronization
1. Server Cleanup Wizard

Here is an example i found if creating a puppet task using powershell scripts:
https://github.com/SeanTecha/powershell_tasks/blob/master/tasks/set_executionpolicy.ps1

**Comment by jblance** [comment]
Interesting functionality - I've not used tasks at all (so far). Is this functionality used a lot?

On a similar note, what about the `puppet resource` functionality - for example to list products or approval rules etc?

**Comment by TraGicCode** [comment]
Hey @jblance ,

You should hang out on the puppet community slack if you are not already on there ( i looked for your handle and could not find you ).  There are already 2 puppet task modules out there that currently handle this:

1. https://github.com/puppetlabs/puppetlabs-resource
1. https://forge.puppet.com/WhatsARanjit/puppeteer

On a side note i've already started working on a powershell task to initiate run of the "Server Cleanup Wizard".  I've never jumped into tasks so this is my first time so i'm not really sure how error handling should be done yet as i'm still looking at what others are doing.  Here is what it looks like in the puppet enterprise console currently.  So far it's rather straight forward since i can use straight-up powershell.

![image](https://user-images.githubusercontent.com/6224270/37573999-726c2ab0-2aeb-11e8-8fd6-073274cd01f5.png)
