### ISSUE TITLE
synchronize_time_of_day not working.

### ISSUE THREAD

**Issue by joeypiccola** [TraGicCode/tragiccode-wsusserver#35]
Hey there, 

I see where you have implemented the `synchronize_time_of_day` functionality below, however, when setting `synchronize_time_of_day` to something other than the default `'03:00:00'` it does not modify the sync time. I'm not sure the idempotency logic allows for it to be run unless `synchronize_automatically` is changed.

Thanks!  

https://github.com/TraGicCode/tragiccode-wsusserver/blob/5d60be343e0db6f2a4c0192b0b44970c9c8012bb/manifests/config.pp#L610-L626

**Comment by TraGicCode** [comment]
Hey @joeypiccola ,

You are indeed correct.  On the outside this module looks great be deep down inside there is some nasty powershell going on ( wsus is automated with a powershell module of course ).  I would be okay with just adding to the unless statement for now to "technically" change all sync related settings even if only one changes.

**Comment by joeypiccola** [comment]
Good to know I read it correctly. I'm not suggesting you make the change thought as my direction has changed a bit and I am not sure the module meets my needs anymore. I'm still going to use WSUS but it's with a SQL backend and a few downstreams (for which the module wasn't really built for).
