### ISSUE TITLE
DSC Resource check fails

### ISSUE THREAD

**Issue by mattinmelbourne** [TraGicCode/tragiccode-wsusserver#37]
when specifying:
include_management_console         => false,
the DSC module still does a Test-TargetResource for windowsresource 'UpdateServices-UI', this feature is not available in core.the code should be updated so that when setting include_management console to false, it does not run that check which causes the module to fail.
![image](https://user-images.githubusercontent.com/26353158/69616876-705f1700-108b-11ea-9383-ed447323f351.png)

**Comment by TraGicCode** [comment]
Hey @Phatix ,

Do you know what fact we could key off of in order to handle this for windows core editions?

**Comment by mattinmelbourne** [comment]
@TraGicCode you can test from registry... from MS website: "test if Server Core is running is to check the registry under **HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion** for the value of **InstallationType**. If it is set to "**Server Core**", then the Server Core installation option is installed."

**Comment by TraGicCode** [comment]
Hey @Phatix ,

Sounds like what we need is a customfact that reads the registry.  Are you up for tackling this?

**Comment by mattinmelbourne** [comment]
I would of thought that if you set the install_management_tools => false, then it wouldn't check to see if that feature was available?

**Comment by TraGicCode** [comment]
Closing since this module has been migrated off dsc resources
