### ISSUE TITLE
Management of built in computer target groups fails for non English Windows

### ISSUE THREAD

**Issue by bornmanm** [TraGicCode/tragiccode-wsusserver#40]
Hello, 
on a non English (in my case German) Windows the powershell provider for computer target groups does not recognize that the built in groups already exist as their names are different from the English ones and then fails to create it. The debug log looks like this:

```
Debug: json parsed computer target groups are [{"id"=>"a0a08746-4dbe-4a37-9adf-9e7652c0b421", "name"=>"Alle Computer"}, {"id"=>"b73ca6ed-5727-47f3-84de-015e03f6a88a", "name"=>"Nicht zugewiesene Computer"}]
Debug: Checking if All Computers exists
Debug: Creating All Computers
Debug: Executing: 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe (Get-WsusServer).CreateComputerTargetGroup('All Computers')
'
Error: Execution of 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe (Get-WsusServer).CreateComputerTargetGroup('All Computers')
' returned 1: Ausnahme beim Aufrufen von "CreateComputerTargetGroup" mit 1 Argument(en):  "Eine Gruppe mit diesem Namen existiert bereits."
```

Replacing the English group names with the German ones in `built_in_computer_target_groups.pp` fixes the problem for me, so a solution might be to allow custom arrays instead of `['All Computers', 'Unassigned Computers']`.

Thanks in advance!

**Comment by TraGicCode** [comment]
Hey @bornmanm ,

I think there might be some "indentifiers" that can be used to identify the built-in groups instead of using strings which are language dependent.  

Thanks for raising this issue.  I will trying and look into this soon to see if it's an easy fix.

**Comment by TraGicCode** [comment]
Sorry for getting back so late to this but would you be able to submit a Pr for this fix?
