### ISSUE TITLE
wsusserver::approvalrule Can't set "Windows 10, version 1903 and later" as a product type

### ISSUE THREAD

**Issue by mike406** [TraGicCode/tragiccode-wsusserver#41]
When setting 'Windows 10, version 1903 and later' in the products list it will only choose 'Windows 10' in the WSUS approval rules

```
        wsusserver::approvalrule { 'Automatic Approval for all Updates Rule':
                ensure          => 'present',
                enabled         => true,
                classifications => $classifications,
                products        => ['Windows 10, version 1903 and later', 'Windows 10 and later drivers'],
                computer_groups => ['AutoApproval']
        }
```

![image](https://user-images.githubusercontent.com/3455235/86496426-6735d700-bd4b-11ea-9a34-2287a0e0f7ca.png)

**Comment by TraGicCode** [comment]
Hey @mike406 ,

Is this something you are able to take a stab at?

**Comment by mike406** [comment]
EDIT: I just realized that the code on Puppet forge contains your old code where you are doing the string split with the comma instead of the semicolon that you have in your  current commit here.

Quite bizarre, I tried running the powershell commands you have in the "update-wsus-approvalrule-products-${rule_name}" exec block manually on my WSUS server and I can set the "Windows 10, version 1903 and later" product sucessfully. I wonder if something is having issues parsing the comma before the array gets to the exec block. When running it through Puppet it appears to just take the "Windows 10" part of the string from "Windows 10, version 1903 and later" and sends that to the approval rule.

**Comment by TraGicCode** [comment]
Hey @mike406 ,

Sounds like I need to cut a release. I’ll do this and let you know so you can see if your issue is resolved.

**Comment by TraGicCode** [comment]
Hey @mike406 ,

Can you go give 1.1.3 a shot?  I uploaded it to the forge

https://forge.puppet.com/tragiccode/wsusserver

**Comment by mike406** [comment]
@TraGicCode Sorry for late reply, I updated to the new version of your module that change is working. Thank you
