### ISSUE TITLE
manifest

### ISSUE THREAD

**Issue by eevans6913** [TraGicCode/tragiccode-wsusserver#44]
I am new to puppet so I need some advice. In my /root/.puppetlabs/bolt/modules/wsusserver/manifests I have several manifests already in place; approvalrule.pp  built_in_computer_target_groups.pp  config.pp  init.pp  install.pp  params.pp  service.pp, do I add the code to one of these or create a new one. I apologize for my noobieness.

**Comment by mike406** [comment]
I've not used Bolt but I do not think this module supports Bolt. You need to install and configure a Puppet Server (either with Puppet Open Source free or a paid version of Puppet Enterprise) as well as install Puppet Agents on your client machines that link back to your server. You install modules on your server and create your own manifests with Puppet code that utilize modules to perform tasks on your clients. You generally do not edit the modules themselves.
