### ISSUE TITLE
Please consider supporting puppetlabs-stdlib version > 5.1.0

### ISSUE THREAD

**Issue by mike406** [TraGicCode/tragiccode-wsusserver#45]
Hello, would it be possible to make this module compatible with version 5.1.0 or higher of the stdlib module? Being compatible with 4.x only it closes the door to many other modules I have been interested in using. I have not yet tried to force version 5.1.0 to see if it breaks anything in wsusserver however.

**Comment by TraGicCode** [comment]
Hey mike,

can you subir a Pr for this?
