### ISSUE TITLE
Windows Server 2019 and 10 product is not correctly chosen anymore due to duplicate products being listed

### ISSUE THREAD

**Issue by mike406** [TraGicCode/tragiccode-wsusserver#46]
This is more the fault of MS and their crappy naming conventions but the 'wsus-config-update-products' does not select Windows Server 2019 correctly. The reason is because MS stupidly has two products listed with the name "Windows Server 2019". You can see this if you run the command `(Get-WsusServer).GetUpdateCategories() | where { $_.Type -eq 'Product' } | findstr /i 2019`

You will see there is a Windows Server 2019 with description "Category for Windows Server 2019" as well as a second one with description "Windows Server 2019 (RS5 Server) and above". The exec routine chooses the first one, but when looking in the WSUS Management Console the desired product is not checked off as it actually uses the other Windows Server 2019 product with the second description.

**Comment by mike406** [comment]
It looks like the same thing happened with Windows 10, version 1903 and later. There are two of them now with the newer one released on 12/8/2020.

**Comment by mike406** [comment]
Sorry to keep adding additional comments, the edit button is broken for me for some reason. I pulled out the products from their listings. It appears that on 12/8/2020 Microsoft released new products for both "Windows 10, version 1903 and later" and "Windows Server 2019" products (there are probably more but these are the only 2 my organization cares about). The problem seems to be that the Puppet exec routine hits the first one it encounters, and the first one it encounters does not always seem to be the one that you want.
```
Type                      : Product
ProhibitsSubcategories    : True
ProhibitsUpdates          : False
UpdateSource              : MicrosoftUpdate
UpdateServer              : Microsoft.UpdateServices.Internal.BaseApi.UpdateServer
Id                        : 6e56e6da-f22f-47c9-97b4-510153a06740
Title                     : Windows Server 2019
Description               : Category for Windows Server 2019
ReleaseNotes              : 
DefaultPropertiesLanguage : 
DisplayOrder              : 2147483647
ArrivalDate               : 12/8/2020 4:00:09 AM

Type                      : Product
ProhibitsSubcategories    : True
ProhibitsUpdates          : False
UpdateSource              : MicrosoftUpdate
UpdateServer              : Microsoft.UpdateServices.Internal.BaseApi.UpdateServer
Id                        : f702a48c-919b-45d6-9aef-ca4248d50397
Title                     : Windows Server 2019
Description               : Windows Server 2019 (RS5 Server) and above
ReleaseNotes              : 
DefaultPropertiesLanguage : 
DisplayOrder              : 2147483647
ArrivalDate               : 5/20/2020 8:10:10 PM

Type                      : Product
ProhibitsSubcategories    : True
ProhibitsUpdates          : False
UpdateSource              : MicrosoftUpdate
UpdateServer              : Microsoft.UpdateServices.Internal.BaseApi.UpdateServer
Id                        : 8a3cbc4a-5334-40d4-a06e-6da96022ae3b
Title                     : Windows 10, version 1903 and later
Description               : Windows 10, version 1903 and later (19H1+)
ReleaseNotes              : 
DefaultPropertiesLanguage : 
DisplayOrder              : 2147483647
ArrivalDate               : 12/8/2020 4:00:09 AM

Type                      : Product
ProhibitsSubcategories    : True
ProhibitsUpdates          : False
UpdateSource              : MicrosoftUpdate
UpdateServer              : Microsoft.UpdateServices.Internal.BaseApi.UpdateServer
Id                        : b3c75dc1-155f-4be4-b015-3f1a91758e52
Title                     : Windows 10, version 1903 and later
Description               : Windows 10, version 1903 and later (19H1+)
ReleaseNotes              : 
DefaultPropertiesLanguage : 
DisplayOrder              : 2147483647
ArrivalDate               : 5/20/2020 8:10:06 PM
```

**Comment by TraGicCode** [comment]
Hey @mike406 ,

Would it be possible for you to submit a PR with the required changes?

**Comment by mike406** [comment]
Giving it a shot now. The duplicate products for "Windows 10, version 1903 and later" and "Windows Server 2019" are not actually hidden as I first thought. They are two products with the same name, but in different categories. They exist both under the "Developer Tools, Runtimes, and Redistributables" as well as the "Windows" category. So it seems it is going to be tricky to determine which one the user really wants selected...I could change the code to select all that match rather than the first one it encounters but that will end up selecting more than what the user may want...But I think that is really the only option here. Microsoft really should be giving distinct product names but it seems they are not anymore. 

Unless the module is changed to instead of using product names, that their ID numbers are used instead.

**Comment by amr952** [comment]
I submitted a PR with the required changes. The code I submitted took the route of selecting all products that match the name.

As Mike said the entire code could be refactored to provide ID numbers instead.

**Comment by mike406** [comment]
@amr952 There's a much simpler way to do that. Just change the .add to use .addRange and removing the Select-Object -First 1

This single change was enough in my tests to get all matches
`[void]\$NewProducts.addRange( (\$allPossibleProducts | Where-Object {\$_.Title -eq \$product -and \$_.type -eq \$Type}) )`

Additionally, the same thing happens in approval rules as well (except it is technically the exact opposite problem). I made the following change in approvalrule.pp in the update-wsus-approvalrule-products-${rule_name} onlyif block. The change is the "-Unique" parameter. It is needed because without it, the exec block will continuously run when there are duplicate products selected in the approval rule. This makes sure the currently selected products list is stripped of duplicates so that it matches up with what the user puts into their manifest for desired products.
`\$currentApprovalCategories = \$approvalRule.GetCategories() | Select-Object -ExpandProperty Title -Unique`

I have these changes ready to go and in my production environment. I was going to submit my PR this weekend, but if you would like to that is fine

**Comment by amr952** [comment]
That makes sense and is a great suggestion. I never even thought about using .addRange, my mind went right toward using a For loop. Did you also make updates to the PS script used for Unless? I had to make changes there for it to pickup changes in just one of the product boxes.

I will try out your code tomorrow and verify it works in my environment as well.

**Comment by mike406** [comment]
Yes, I did make a change in the unless block I forgot to mention it. On line 513 and 516 I added an additional pipe to Select-Object -Unique at the end of it. This helps to make sure that the currently enabled products list matches what the user has defined in their manifest when duplicate products are enabled in WSUS, similar to my change in approvalrule.pp

```
\$currentEnabledProductFamilies = (\$wsusServerSubscription.GetUpdateCategories() | Where-Object {\$_.type -eq \"productfamily\"}).Title | Select-Object -Unique

\$currentEnabledProducts = (\$wsusServerSubscription.GetUpdateCategories() | Where-Object {\$_.type -eq \"product\"}).Title | Select-Object -Unique
```

It looks like your change in the Unless block accomplishes the same thing. You are adding the duplicates to $desired_products and $desired_productfamilies whereas I am stripping out the duplicates from $currentEnabledProducts. End result is identical.

**Comment by mike406** [comment]
For clarity, I've attached my modified config.pp and approvalrule.pp files in case you want to test with them directly

[approvalrule.txt](https://github.com/TraGicCode/tragiccode-wsusserver/files/5817587/approvalrule.txt)
[config.txt](https://github.com/TraGicCode/tragiccode-wsusserver/files/5817740/config.txt)

**Comment by amr952** [comment]
Great, thank you for sending those over. I am working on testing a new WSUS server today so I will test those files out.

**Comment by mike406** [comment]
@amr952 Just checking if you have completed your tests.

**Comment by abreniaux** [comment]
Hi guys,

Any news from your test?
I am stucked with the bad product name for Windows Server 2019.
Regards

**Comment by mike406** [comment]
@abreniaux There is a PR out that is ready to be merged that addresses the issue so I think it should be ready very soon.
