### ISSUE TITLE
Invalid product name supplied - Windows Server 2008 R2

### ISSUE THREAD

**Issue by abreniaux** [TraGicCode/tragiccode-wsusserver#51]
Hello,

I run the new 1.1.4 version of your module and get an issue when I select "Windows 2008 R2" as a product on my puppetfile.

Here is my code:
 products                           => [
      'Windows Server 2008 R2',
      'Windows Server 2012 R2',
      'Windows Server 2016',
      'Windows Server 2019',
      'Microsoft Defender Antivirus',
      'Microsoft SQL Server 2012',
      'Microsoft SQL Server 2016',
      'Microsoft SQL Server 2017',
      'Microsoft SQL Server 2019',
      'Windows Server Manager – Windows Server Update Services (WSUS) Dynamic Installer',
    ],

All other products worked fine if I put a comment or delete "Windows Server 2008 R2" line.

But the fact is that the issue avoid the execution of the update classification:
 update_classifications             => [
      'Critical Updates',
      'Definition Updates',
      'Security Updates',
      'Service Packs',
      'Update Rollups',
      'Updates',
      'Upgrades',
    ],

And the puppet agent finished with 1 failure.

Windows events application logs returned error and last _run report log noticed this error:

logs:
- level: notice
  message: "Invalid product name supplied - Windows Server 2008 R2\r"
  source: "/Stage[main]/Wsusserver::Config/Exec[wsus-config-update-products]/returns"
 R
It's like the Windows Server 2008 R2 isn't present at all on my wsuserver.

When I run the following PS command:

(Get-WsusServer).GetUpdateCategories() |  Where-Object {$_.Title -contains "Windows Server 2008 R2"}

Type                      : Product
ProhibitsSubcategories    : True
ProhibitsUpdates          : False
UpdateSource              : MicrosoftUpdate
UpdateServer              : Microsoft.UpdateServices.Internal.BaseApi.UpdateServer
Id                        : fdfe8200-9d98-44ba-a12a-772282bf60ef
Title                     : Windows Server 2008 R2
Description               : Windows Server 2008 R2 Category
ReleaseNotes              :
DefaultPropertiesLanguage :
DisplayOrder              : 2147483647
ArrivalDate               : 5/24/2019 8:10:39 AM

I could see that 2008 R2 is present on my update categories.

Do you have a solution for that or noticed a similar issue?
Regards.

**Comment by TraGicCode** [comment]
@amr952 & @mike406 ,

Sounds like this is a bug from the PR i merged.  Do one of you have time to resolve this?

**Comment by mike406** [comment]
Looking into it...standby

Edit: I have no issues adding Server 2008 R2
![Capture](https://user-images.githubusercontent.com/3455235/112365845-7f210280-8cae-11eb-87a9-eb8311e424cc.PNG)
![Capture2](https://user-images.githubusercontent.com/3455235/112365852-80eac600-8cae-11eb-9143-efddd187e2b2.PNG)

**Comment by mike406** [comment]
@abreniaux  I see an extra "\r" character in the log output you posted. 
message: "Invalid product name supplied - Windows Server 2008 R2 **\r** "

Edit your manifest by deleting the line with "Windows Server 2008 R2" and manually type it.

**Comment by PiR-B** [comment]
Hi,

I also have this strange behaviour from my WSUS with region set as "French (Switzerland)"

```powershell
ForEach ($product in (Get-WsusServer).GetUpdateCategories() | Where-Object {$_.type -eq "product"}) {
        echo $product.Title | Format-Hex
}
```
output 

```bash
00000000   57 69 6E 64 6F 77 73 20 53 65 72 76 65 72 3F 32  Windows Server?2
00000010   30 30 38 20 52 32                                008 R2          
```

Just copy (with the strange character) the product you need from the output of the code below and paste it in your product list
```powershell
ForEach ($product in (Get-WsusServer).GetUpdateCategories() | Where-Object {$_.type -eq "product"}) {
        echo $product.Title
}
```

Or change your LANG environment variable
More information : https://puppet.com/docs/puppet/7.5/config_about_settings.html#setting-your-locale-on-windows

**Comment by mike406** [comment]
> Hi,
> 
> I also have this strange behaviour from my WSUS with region set as "French (Switzerland)"
> 
> ```powershell
> ForEach ($product in (Get-WsusServer).GetUpdateCategories() | Where-Object {$_.type -eq "product"}) {
>         echo $product.Title | Format-Hex
> }
> ```
> 
> output
> 
> ```shell
> 00000000   57 69 6E 64 6F 77 73 20 53 65 72 76 65 72 3F 32  Windows Server?2
> 00000010   30 30 38 20 52 32                                008 R2          
> ```
> 
> Just copy (with the strange character) the product you need from the output of the code below and paste it in your product list
> 
> ```powershell
> ForEach ($product in (Get-WsusServer).GetUpdateCategories() | Where-Object {$_.type -eq "product"}) {
>         echo $product.Title
> }
> ```
> 
> Or change your LANG environment variable
> More information : https://puppet.com/docs/puppet/7.5/config_about_settings.html#setting-your-locale-on-windows

Likely not the same issue. His extra character is in his Puppet Manifest, not in WSUS.

**Comment by abreniaux** [comment]
Hello,

When I set the WinSystemLocal variable to en-US on my WSUS server, the parameters are applied without issue.
The main thing to remember is that puppet service will run by default with the "Administrator" account on Windows server so keep in mind that the execution language has to be set in en-US if you want to avoid translation issue on products name.
Regards.

**Comment by abreniaux** [comment]
@PiR-B solution fixed my issue + the trick to set WinSystemLocal variable to en-US for Administrator account which runs the puppet service on Windows server.
Thanks a lot for your time
