### ISSUE TITLE
update_classifications dosent work

### ISSUE THREAD

**Issue by trondk** [TraGicCode/tragiccode-wsusserver#53]
It seems that the update_classifications, dosent work, its creates a no config on the update_classifications i wsus server.
is this a bug ?
im running it on a windows 2016

**Comment by randriksen** [comment]
I'm seeing almost the same thing. the only classification it allows is 'upgrades'

**Comment by randriksen** [comment]
I found out why I was having trouble with this. The wsus server had Norwegian language installed and it gives Norwegian answers to Get-WsusClassification which is used to set the classifications. Using the Norwegian names it works for the classifications.
