### ISSUE TITLE
puppetlabs-dsc is deprecated, consider migrating to puppetlabs-dsc_lite

### ISSUE THREAD

**Issue by mike406** [TraGicCode/tragiccode-wsusserver#56]
Supported DSC module: https://forge.puppet.com/modules/puppetlabs/dsc_lite

Using native powershell commands Get-WindowsFeature and Install-WindowsFeature would do the trick as well.

**Comment by TraGicCode** [comment]
Hey @mike406 ,

This was resolved in #54 .  Is version 1.2.0 not working?

![image](https://user-images.githubusercontent.com/6224270/128892615-827e49b2-b01c-4d3e-a1b8-758cdc9cab23.png)

**Comment by mike406** [comment]
Sorry @TraGicCode I may have been blind and completely missed the new release.
