### ISSUE TITLE
Add support for proxies

### ISSUE THREAD

**Issue by rick-bennett** [TraGicCode/tragiccode-wsusserver#62]
There doesn't seem to be an existing method to configure the proxy settings. For those with devices behind firewalls, this would be a helpful enhancement to have (included before the initial sync).

`$config = (Get-WsusServer).GetConfiguration()`
`$config.ProxyName = ${proxy_name}`
`$config.ProxyServerPort = ${proxy_port}`
`$config.UseProxy = $true`
`$config.Save()`

**Comment by TraGicCode** [comment]
Hey @RFBennet ,

would you be able to submit a PR with this added feature?
