### ISSUE TITLE
wsusserver: Ability to use a proxy 

### ISSUE THREAD

**Issue by jblance** [TraGicCode/tragiccode-wsusserver#7]
Key config params:
`UseProxy`
`ProxyName`
`ProxyServerPort`

Optional params:
`AnonymousProxyAccess`
`ProxyUserName`
`ProxyUserDomain`
`ProxyPassword`
`HasProxyPassword`
`AllowProxyCredentialsOverNonSsl`

**Comment by stuartrobert** [comment]
The PR #19 looks like it resolves this, but it didn't get merged? Could it get reopened and merged to resolve this?
